name: skeleton_viewer
description: A Flutter app for viewing skeleton data from AltumView cameras
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  mqtt_client: ^10.0.0
  provider: ^6.0.5
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true